spring:
  application:
    name: tarefas
  datasource:
    url: jdbc:mysql://localhost:3306/listatarefas
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
